services:
  qe_cpu:
    build: 
      context: ./qe
      args:
        QE_VER: ${QE_VER}
        BUILD_THREADS: ${BUILD_THREADS}
    container_name: qe.${QE_VER}-cpu
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - "${DATA_DIRECTORY}:/mnt/data:Z"
